### ISSUE TITLE
Can't rename the patch

### ISSUE THREAD

**Issue by ghost** [christofmuc/KnobKraft-orm#29]
Hi!
I have a problem - can't rename the patch
It says it got renamed but in fact its not
![image](https://user-images.githubusercontent.com/75297247/101873035-4e9dd880-3b97-11eb-9bc7-a1ea9180da0a.png)
![image](https://user-images.githubusercontent.com/75297247/101873074-5cebf480-3b97-11eb-9735-5a3ee5b1b7b0.png)

**Comment by christofmuc** [comment]
Well spotted, that's actually a missing feature! I thought I had done it, but actually it is still on the to do list. Will fix with the next release, and let you know here!

**Comment by christofmuc** [comment]
That was fixed and released today with version 1.9.0

**Comment by dukzcry** [comment]
@christofmuc Unfortunately still an issue for me with 1.9.0. I've made a video 

https://user-images.githubusercontent.com/333093/102722153-4a4c8a80-4310-11eb-83e4-d7a2bcffe17c.mp4

**Comment by christofmuc** [comment]
Oh. Hm. Works for me. I see you are on Linux. Can you build a debug version and try that?

**Comment by christofmuc** [comment]
You did refresh the submodules I trust before rebuilding?

**Comment by dukzcry** [comment]
> Can you build a debug version and try that?

I will build it now and come back to you

> You did refresh the submodules I trust before rebuilding?

In distro I use submodule revisions are fixed on versions that were used for release tree, e.g. for 1.9.0
![image](https://user-images.githubusercontent.com/333093/102806673-59920d80-43ce-11eb-9c72-3582ef04b57c.png)
I cannot change that, this is to make builds deterministic

**Comment by christofmuc** [comment]
Ok, yes, that is correct. The other error would only happen if you do a manual "git pull" and then forget to do a "git submodule update" or whatever the command is to also update them. I also use SourceTree App, which does it most of the times correctly.

I would expect that there is some kind of assertion happending when the rename doesn't work, ideally you could start a debugger to see what happens.

**Comment by dukzcry** [comment]
Hmm, nothing interesting here
![image](https://user-images.githubusercontent.com/333093/102810361-a4168880-43d4-11eb-9b1e-b17eff41d8d7.png)
I've built with
```
makeFlags: "CFLAGS+=-Og" "CFLAGS+=-ggdb"
cmakeFlags: "-DCMAKE_BUILD_TYPE=Debug"
``
BTW will reboot to Windows now to see how it works there :)

**Comment by dukzcry** [comment]
Same thing under Windows with 1.9.0 release. Maybe I'm using this feature completely wrong? I just want to rename the patch in library

https://user-images.githubusercontent.com/333093/102812813-cad6be00-43d8-11eb-9717-8fb4c7f5f642.mp4

**Comment by christofmuc** [comment]
Something weird is happening here, you're doing it right, but my log reads e.g.

20:09:20: Changed patch name to Chopper2
20:09:20: Updated 1 patches in the database with new names

The second line is missing in your example, so there is a silent error between the two.

Did you only try it with patches you just retrieved from the synth, or also with patches you loaded from disk? Maybe try loading the attached sysex file and then rename it, that works on my Windows machine on KnobKraft 1.9.0
[chopper.zip](https://github.com/christofmuc/KnobKraft-orm/files/5726034/chopper.zip)

**Comment by dukzcry** [comment]
With your file its fine :)
```
22:17:32: Changed patch name to Chopper2
22:17:32: Updated 1 patches in the database with new names
```
and the patch got renamed

**Comment by christofmuc** [comment]
Ok, I found it. It is a very special case in that you cannot rename a patch that has the default name. The original idea is that if something is called "Init Voice", you don't want to use that name to overwrite some already given name in the database, because that might be better. The weird error is that it calculates the new name as "Init Voice", even if you called it "Test".

I will fix it. Rest assured all other patches not called "Init Voice" will be able to be renamed already, if I understand this now correctly :-)

Thanks for you help, and no, this is not a Linux problem, but a Christof problem!

**Comment by dukzcry** [comment]
Thank you! This is indeed a special case. I just often have a "Init Voice" for import because I like sculpting on the synth using init voice :)

**Comment by Andy2No** [comment]
Are you saying it's meant to stop a patch called "Init Voice" being renamed to something else, or to stop a patch being renamed as "Init Voice"?

It's probably not uncommon to start with an Init patch, make some edits, then save it without altering the name, because that can be a pain, on some synths.  If someone was relying on a librarian to edit the names, they'd expect to be able to change Init Voice to something else.

**Comment by christofmuc** [comment]
Yes, it is a bug in that you currently cannot rename a patch that is called "Init Voice" to something else. It's a nasty bug in that it only fires in this one direction, and my tests only were renaming anything else. Of course you should be able to rename Init Voice to something useful, but the logic was there to prevent something else to be automatically renamed back to "Init Voice", in case you reimport a patch where you had manually already given a better name without sending it back into the synth.

It's a bit of an obscure case we hit here, and the bug I just fixed was even more obscure (inadvertedly had done a shallow copy with shared pointers where a deep copy was wanted).

**Comment by christofmuc** [comment]
Didn't mean to close, waiting for release 1.9.1

**Comment by christofmuc** [comment]
Fixed in 1.10.0

**Comment by dukzcry** [comment]
Thanks! Unfortunately still can't rename
```
08:30:29: DATABASE ERROR: SQL Exception Unknown column name.
08:30:29: DATABASE ERROR: SQL Exception UNIQUE constraint failed: patches.md5
```

**Comment by christofmuc** [comment]
Wow, sorry, that was a build problem in that the whole 1.10.0 build could not write into the database. I just made a hotfix 1.10.1 - it worked on my reface DX, I explicitly tested it, so I really hope this works for you now :-(

**Comment by dukzcry** [comment]
@christofmuc All is fine now, thank you much!!!

**Comment by christofmuc** [comment]
@dukzcry Thank you for bearing with me, this was tricky!
